apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: devops-ev1-api-ingress
  namespace: devops-ev1
  labels:
    app.kubernetes.io/name: devops-ev1
    app.kubernetes.io/component: api
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: devops-ev1
      app.kubernetes.io/component: api
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 5000
