apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-ev1-api
  namespace: devops-ev1
  labels:
    app.kubernetes.io/name: devops-ev1
    app.kubernetes.io/component: api
automountServiceAccountToken: false
